sudo: false
language: node_js
node_js:
  - stable
install:
  - npm install
notifications:
  email: false
script:
  - 'npm run coverage'
after_success:
  - 'npm run coveralls'
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE elite;' -U postgres
  - psql -c 'CREATE TABLE members(
    id serial NOT NULL PRIMARY KEY,
    name varchar(200) NOT NULL,
    email varchar(100) not null unique,
    location varchar(100) default 'ETE',
    shares bigint default 1,
    joined timestamp not null,
    committee varchar(100) unique,
    img varchar(255) default 'https://firebasestorage.googleapis.com/v0/b/learn-firebase-bbe9f.appspot.com/o/profiles%2Falain%40gmail.com.jpg?alt=media&token=2a01735f-6560-45ef-86b2-b6536dcfcb40'
    );' -U postgres
